### ISSUE TITLE
Cant Install package

### ISSUE THREAD

**Issue by ktgoetz** [ABindoff/TwilightFree#5] opened 2018-08-14 02:17 UTC
When i try to install i keep getting the following error - others at my institution have also had the same issue.  Please advise...

devtools::install_github("ABindoff/TwilightFree")
Downloading GitHub repo ABindoff/TwilightFree@master
from URL https://api.github.com/repos/ABindoff/TwilightFree/zipball/master
Installing TwilightFree
"C:/PROGRA~1/R/R-34~1.2/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/goetzkt/AppData/Local/Temp/RtmpCam3K6/devtools2b14282b5c0e/ABindoff-TwilightFree-1f35126"  \
  --library="C:/Users/goetzkt/Documents/R/win-library/3.4" --install-tests 

* installing *source* package 'TwilightFree' ...
** R
Error in parse(outFile) : 
  C:/Users/goetzkt/AppData/Local/Temp/RtmpCam3K6/devtools2b14282b5c0e/ABindoff-TwilightFree-1f35126/R/drawTracks.R:20:24: unexpected symbol
19:                        line.col = "grey60"
20:                        main
                           ^
ERROR: unable to collate and parse R files for package 'TwilightFree'
* removing 'C:/Users/goetzkt/Documents/R/win-library/3.4/TwilightFree'
Installation failed: Command failed (1)

**Comment by ABindoff** [comment] 2018-08-15 08:33
Thanks for reporting this, it was a missing comma. Now fixed and pushed to the repo. Please let me know when you are able to install successfully so I may close this issue.

Also, let me know if you have any trouble estimating positions, happy to return the favour.

Aidan

**Comment by ABindoff** [comment] 2018-08-23 04:47
Hi ktgoetz,  were you able to install the package after I pushed the changes?  I would like to close this issue if you did.

**Comment by ktgoetz** [comment] 2018-08-23 08:05
Thank you so much!  All fixed. I appreciate your help.
Cheers,

Kim

**Comment by ABindoff** [comment] 2018-08-23 08:12
Thanks Kim, let me know if you need any further help!

**Comment by ktgoetz** [comment] 2018-08-23 08:34
can you tell me why i get the error when running your example starting at line 135 =)?
> model <- TwilightFree(d.lig,
+                       alpha=c(1, 1/25),
+                       beta=c(1, 1/5),
+                       zenith = zen, threshold = thresh, 
+                       deployed.at = deployed.at,
+                       retrieved.at = retrieved.at)
> fit <- SGAT::essie(model,grid,epsilon1=1.0E-4, epsilon2 = 1E-6)
Error in sst[[indices[k]]] : object 'indices' not found

Thanx!

**Comment by ktgoetz** [comment] 2018-08-23 08:35
and i have no idea why it pasted like that.

**Comment by ABindoff** [comment] 2018-08-23 08:53
Hi

**Comment by ABindoff** [comment] 2018-08-23 09:04
Hi Kim,  I can receive notifications but they're not showing up here because I had closed the issue. Probably best to email me via the email address on the paper in MEE.

**Comment by ABindoff** [comment] 2018-08-23 09:14
I'm not really sure why you're having trouble.  I wasn't able to reproduce the error using a clean install, but maybe I looked at a different example?  If there is no data in the d.lig$Temp column and you haven't given the model a raster with SST data in it it shouldn't be looking for `indices` at all.  Is it possible you missed a line?

I suggest you go through the "Using SST and sightings" example and see if you have any issues with that. It's a more recent tutorial anyway.

**Comment by ABindoff** [comment] 2018-08-24 00:25
Hi Kim,  closing this issue now but if you have any trouble with the "Using SST and sightings" example from the tutorials please let me know by email or by opening a new issue and I will have another look.

**Closed as completed by ABindoff** 2018-08-24 00:25 UTC
